# 混淆矩阵 Confusion Matrix

In [1]:
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

X=digits.data
y=digits.target


In [3]:
y[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y[y<9]=0
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 9])

In [5]:
y[y==9]=1
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test =train_test_split(X, y , random_state=666)

In [8]:
X_train.shape

(1347, 64)

In [9]:
X_test.shape

(450, 64)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log_reg=LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

0.97555555555555551

In [12]:
y_predict=log_reg.predict(X_test)

In [13]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [14]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [15]:
def TN(y_true, y_predict):
    assert len(y_true)==len(y_predict)
    return np.sum( (y_true==0) & (y_predict==0) )

In [16]:
tn = TN(y_test, y_predict)

In [17]:
def FP(y_true, y_predict):
    return np.sum( (y_predict==1) & (y_true==0) )

In [18]:
fp = FP(y_test, y_predict)

In [19]:
def FN(y_true, y_predict):
    return np.sum( (y_true==1) & (y_predict==0) )

In [20]:
fn = FN(y_test, y_predict)

In [21]:
def TP(y_true, y_predict):
    return np.sum( (y_true==1) & (y_predict==1) )

In [22]:
tp= TP(y_test, y_predict)

In [23]:
precision= tp/ (tp + fp )

In [24]:
recall=tp/(tp+fn)

In [25]:
precision

0.94736842105263153

In [26]:
recall

0.80000000000000004

In [27]:
tp

36

In [28]:
fn

9

In [29]:
def confusion_matrix(y_true, y_predict):
    return np.array([[
        TN(y_true, y_predict), FP(y_true, y_predict)
    ],[
        FN(y_true, y_predict), TP(y_true, y_predict)
    ]])

In [30]:
confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

# sklearn中的混淆矩阵, precision, recall

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [33]:
from sklearn.metrics import precision_score

In [34]:
precision = precision_score(y_test, y_predict)

In [35]:
from sklearn.metrics import recall_score

In [36]:
recall = recall_score(y_test, y_predict)

In [37]:
def f1_score(precision, recall):
    try:
        return 2*precision*recall/(precision+recall)
    except:
        return 0.0

In [38]:
f1=f1_score(precision, recall)

In [39]:
f1

0.86746987951807231

In [40]:
from sklearn.metrics import f1_score

In [42]:
f1_score(y_test, y_predict)

0.86746987951807231